-- The vehicle catalog: brand → model → generation → variant.
--
-- Read-only reference data. Everything a user owns points into it, which is
-- what makes "does this wheel fit my car" a comparison between numbers rather
-- than a guess about two strings.
--
-- The rows themselves are a separate content project and are not seeded here.
--
-- Conventions established by this migration, followed by every later one:
--
--   * UUID primary keys, generated by the application as version 7. v7 leads
--     with a timestamp, so inserts land at the end of the index instead of
--     scattering across it the way v4 does, and the value is safe to put in a
--     URL — unlike a serial, which tells anyone who looks how many rows exist.
--   * TIMESTAMPTZ, never TIMESTAMP. The server is UTC and the users are in
--     three Indonesian time zones.
--   * created_at and updated_at on every table, with updated_at maintained by
--     a trigger so no writer has to remember it.
--   * A slug unique within its parent, so a URL can read
--     /toyota/avanza/w100/1-5-g-cvt without exposing an id.
--   * Every foreign key gets an index. PostgreSQL creates one for a primary
--     key and for a unique constraint, but never for a foreign key — and a
--     missing one turns a parent delete into a sequential scan of the child.

CREATE TABLE brands (
    id          UUID PRIMARY KEY,
    name        TEXT        NOT NULL,
    slug        TEXT        NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE vehicle_models (
    id          UUID PRIMARY KEY,
    brand_id    UUID        NOT NULL REFERENCES brands (id) ON DELETE RESTRICT,
    name        TEXT        NOT NULL,
    slug        TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (brand_id, slug)
);

CREATE INDEX vehicle_models_brand_idx ON vehicle_models (brand_id);

CREATE TABLE vehicle_generations (
    id          UUID PRIMARY KEY,
    model_id    UUID        NOT NULL REFERENCES vehicle_models (id) ON DELETE RESTRICT,
    name        TEXT        NOT NULL,
    -- Chassis code — FD1, W100, ZE4. What owners actually call their car, and
    -- often the only term a forum thread uses.
    code        TEXT,
    slug        TEXT        NOT NULL,
    year_start  SMALLINT    NOT NULL,
    -- NULL means still in production. A sentinel year would eventually be
    -- compared against and quietly exclude current cars.
    year_end    SMALLINT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (model_id, slug),
    CONSTRAINT vehicle_generations_years_ordered
        CHECK (year_end IS NULL OR year_end >= year_start)
);

-- "I have a 2019 Avanza" resolves to a generation by year, which is the first
-- thing that happens when someone adds a car.
CREATE INDEX vehicle_generations_model_years_idx
    ON vehicle_generations (model_id, year_start, year_end);

-- Closed sets, as native types rather than free text. Adding a value later is
-- `ALTER TYPE … ADD VALUE`, which does not break a running older version —
-- it simply never produces the new one. That is the expand direction AC3
-- cares about. Removing a value is genuinely hard, which is the honest cost
-- of saying the set is closed.
CREATE TYPE transmission_kind AS ENUM ('manual', 'automatic', 'cvt', 'dct', 'amt');
CREATE TYPE drivetrain_kind   AS ENUM ('fwd', 'rwd', 'awd', '4wd');
CREATE TYPE fuel_kind         AS ENUM ('petrol', 'diesel', 'hybrid', 'phev', 'electric');

CREATE TABLE vehicle_variants (
    id              UUID PRIMARY KEY,
    generation_id   UUID        NOT NULL REFERENCES vehicle_generations (id) ON DELETE RESTRICT,
    name            TEXT        NOT NULL,
    slug            TEXT        NOT NULL,

    -- Engine. `engine_code` is text because it is an identifier, not a
    -- quantity: 2NR-VE, K20C1, M20A-FKS.
    engine_code     TEXT,
    displacement_cc INTEGER,
    power_hp        SMALLINT,
    torque_nm       SMALLINT,

    transmission    transmission_kind,
    drivetrain      drivetrain_kind,
    fuel            fuel_kind,

    -- The OEM wheel fitment reference, and the reason AC4 exists.
    --
    -- "PCD 5x114.3" is two numbers, not one string: a bolt count and a circle
    -- diameter. Stored as text, every fitment comparison would have to parse
    -- it first, and "5X114.3" and "5x114,3" would be different cars.
    --
    -- Offset is SMALLINT because it is signed — a deep-dish wheel is a
    -- negative ET, and an unsigned column would silently reject exactly the
    -- wheels people modify their cars with.
    pcd_bolt_count  SMALLINT,
    pcd_diameter_mm NUMERIC(5, 1),
    center_bore_mm  NUMERIC(5, 1),
    oem_et_mm       SMALLINT,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (generation_id, slug),

    -- A PCD is meaningless with only half of it recorded, so the two travel
    -- together or not at all.
    CONSTRAINT vehicle_variants_pcd_complete CHECK (
        (pcd_bolt_count IS NULL AND pcd_diameter_mm IS NULL)
        OR (pcd_bolt_count IS NOT NULL AND pcd_diameter_mm IS NOT NULL)
    ),
    CONSTRAINT vehicle_variants_pcd_plausible CHECK (
        pcd_bolt_count IS NULL OR pcd_bolt_count BETWEEN 3 AND 8
    ),
    CONSTRAINT vehicle_variants_displacement_positive CHECK (
        displacement_cc IS NULL OR displacement_cc > 0
    )
);

CREATE INDEX vehicle_variants_generation_idx ON vehicle_variants (generation_id);

-- "Which cars share this bolt pattern" is the fitment engine's core question,
-- and it reads the catalog rather than a user's garage. Partial, because a
-- variant with no PCD recorded can never be an answer to it.
CREATE INDEX vehicle_variants_pcd_idx
    ON vehicle_variants (pcd_bolt_count, pcd_diameter_mm)
    WHERE pcd_bolt_count IS NOT NULL;

CREATE TRIGGER brands_set_updated_at
    BEFORE UPDATE ON brands
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER vehicle_models_set_updated_at
    BEFORE UPDATE ON vehicle_models
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER vehicle_generations_set_updated_at
    BEFORE UPDATE ON vehicle_generations
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER vehicle_variants_set_updated_at
    BEFORE UPDATE ON vehicle_variants
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
