#!/usr/bin/env node
/**
 * Generate the CSS artifacts from `src/tokens.js`.
 *
 * Two outputs, because the two web surfaces consume tokens differently:
 *
 *   dist/tokens.css  plain custom properties, with a dark block — Astro
 *   dist/theme.css   a Tailwind v4 `@theme` block — the backoffice
 *
 * React Native needs neither: it imports `src/tokens.js` directly.
 *
 * The `material`, `edge`, and `ground` groups are deliberately NOT emitted
 * here. They are mobile-only (AM-15), and putting them into theme.css would
 * add custom properties to the backoffice's Tailwind theme that nothing
 * reads. When a web surface needs the material, emit it then.
 *
 * No dependencies and no bundler. This runs on plain Node, which is what
 * keeps the package cheap enough that regenerating is never a chore.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  accent,
  brand,
  dark,
  elevation,
  layout,
  light,
  motion,
  radius,
  semantic,
  spacing,
  type,
  typeMobile,
  typography,
} from "../src/tokens.js";

const here = dirname(fileURLToPath(import.meta.url));
const dist = resolve(here, "..", "dist");

const BANNER = `/* GENERATED by packages/tokens — do not edit.
 * Source: packages/tokens/src/tokens.js
 * Regenerate: cd packages/tokens && node scripts/build.mjs
 */`;

/** kebab-case a camelCase token name: surfaceSubtle -> surface-subtle */
const kebab = (name) => name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

function colorVars(prefix, group) {
  return Object.entries(group).map(([key, value]) => `  --${prefix}-${kebab(key)}: ${value};`);
}

function themeVars(theme) {
  return Object.entries(theme).map(([key, value]) => `  --color-${kebab(key)}: ${value};`);
}

function scaleVars(prefix, scale, unit = "px") {
  return Object.entries(scale).map(([key, value]) => `  --${prefix}-${key}: ${value}${unit};`);
}

/** Composite `font` shorthands, with the family appended so callers write
 *  `font: var(--type-hero);` and get the whole declaration. */
function typeVars(prefix, scale) {
  return Object.entries(scale).map(
    ([key, value]) => `  --${prefix}-${key}: ${value} var(--font-sans);`,
  );
}

/** The theme-independent half of the design system beyond colour: type
 *  shorthands, motion, and the non-floating shadow. `--shadow-soft` is
 *  theme-dependent and defined per theme instead (see the dark blocks). */
function systemVars() {
  return [
    "",
    "  /* Type scale (desktop) */",
    ...typeVars("type", type),
    "",
    "  /* Type scale (mobile) */",
    ...typeVars("type-m", typeMobile),
    "",
    "  /* Elevation — --shadow-soft is redefined per theme */",
    `  --shadow-none: ${elevation.none};`,
    `  --shadow-soft: ${elevation.soft.light};`,
    "",
    "  /* Motion */",
    `  --duration-micro: ${motion.durationMicro};`,
    `  --duration-standard: ${motion.durationStandard};`,
    `  --duration-sheet: ${motion.durationSheet};`,
    `  --ease-out: ${motion.easeOut};`,
  ];
}

/**
 * Plain custom properties.
 *
 * Three theme states, not two. An explicit choice stamps
 * `data-theme` on the root; the default "system" setting stamps nothing,
 * so only `prefers-color-scheme` separates light from dark there. Light
 * is defined on bare `:root`, dark is redefined twice — once behind the
 * media query guarded against an explicit light choice, once behind the
 * explicit dark attribute — so a toggle wins in both directions.
 */
function buildTokensCss() {
  return [
    BANNER,
    "",
    ":root {",
    "  /* Brand and accent — theme-independent */",
    ...colorVars("brand", brand),
    ...colorVars("accent", accent),
    ...Object.entries(semantic).map(([key, value]) => `  --${key}: ${value};`),
    "",
    "  /* Light theme */",
    ...themeVars(light),
    "",
    "  /* Spacing */",
    ...scaleVars("space", spacing),
    "",
    "  /* Radius */",
    ...scaleVars("radius", radius),
    "",
    "  /* Typography */",
    `  --font-sans: ${typography.fontFamily};`,
    `  --font-numeric: ${typography.numericFeature};`,
    ...systemVars(),
    "",
    "  /* Layout */",
    `  --page-padding: ${layout.pagePaddingMobile}px;`,
    `  --container-max: ${layout.containerMaxWidth}px;`,
    `  --touch-target-min: ${layout.touchTargetMin}px;`,
    "}",
    "",
    "@media (prefers-color-scheme: dark) {",
    '  :root:not([data-theme="light"]) {',
    ...themeVars(dark).map((line) => `  ${line}`),
    `    --shadow-soft: ${elevation.soft.dark};`,
    "  }",
    "}",
    "",
    ':root[data-theme="dark"] {',
    ...themeVars(dark),
    `  --shadow-soft: ${elevation.soft.dark};`,
    "}",
    "",
  ].join("\n");
}

/**
 * Tailwind v4 theme block.
 *
 * v4 is CSS-first: there is no JavaScript config, `@theme` declares the
 * design system, and utility classes fall out of the variable names.
 */
function buildThemeCss() {
  return [
    BANNER,
    "",
    '@import "tailwindcss";',
    "",
    "@theme {",
    ...colorVars("color-brand", brand),
    ...colorVars("color-accent", accent),
    ...Object.entries(semantic).map(([key, value]) => `  --color-${key}: ${value};`),
    "",
    ...Object.entries(light).map(([key, value]) => `  --color-${kebab(key)}: ${value};`),
    "",
    ...scaleVars("spacing", spacing),
    "",
    ...Object.entries(radius).map(([key, value]) => `  --radius-${key}: ${value}px;`),
    "",
    `  --font-sans: ${typography.fontFamily};`,
    ...systemVars(),
    "}",
    "",
    "/* Dark theme. Tailwind v4 reads these as the same variables, so every",
    "   utility built on them flips without a `dark:` prefix on each one. */",
    "@media (prefers-color-scheme: dark) {",
    '  :root:not([data-theme="light"]) {',
    ...Object.entries(dark).map(([key, value]) => `    --color-${kebab(key)}: ${value};`),
    `    --shadow-soft: ${elevation.soft.dark};`,
    "  }",
    "}",
    "",
    ':root[data-theme="dark"] {',
    ...Object.entries(dark).map(([key, value]) => `  --color-${kebab(key)}: ${value};`),
    `  --shadow-soft: ${elevation.soft.dark};`,
    "}",
    "",
  ].join("\n");
}

await mkdir(dist, { recursive: true });
await writeFile(resolve(dist, "tokens.css"), buildTokensCss(), "utf8");
await writeFile(resolve(dist, "theme.css"), buildThemeCss(), "utf8");

console.log("wrote dist/tokens.css and dist/theme.css");
